import { BookEntity } from "../entity/book.entity";

export const books: BookEntity[] = [
  {
    id: 1,
    title: "Things Fall Apart",
    author: "Chinua Achebe",
    realYears: "1958",
    year: "1958",
    country: "Nigeria",
    language: "English",
    pages: 209,
    wikipediaLink: "https://en.wikipedia.org/wiki/Things_Fall_Apart",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fthings-fall-apart.jpg?alt=media",
  },
  {
    id: 2,
    title: "Fairy tales",
    author: "Hans Christian Andersen",
    realYears: "1835-37",
    year: "1836",
    country: "Denmark",
    language: "Danish",
    pages: 784,
    wikipediaLink:
      "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Ffairy-tales.jpg?alt=media",
  },
  {
    id: 3,
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    realYears: "1308-1321",
    year: "1315",
    country: "Italy",
    language: "Italian",
    pages: 928,
    wikipediaLink: "https://en.wikipedia.org/wiki/Divine_Comedy",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fthe-divine-comedy.jpg?alt=media",
  },
  {
    id: 4,
    title: "The Epic Of Gilgamesh",
    author: "Unknown",
    realYears: "18th - 17th century BCE",
    year: "-1700",
    country: "Sumer and Akkadian Empire",
    language: "Akkadian",
    pages: 160,
    wikipediaLink: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fthe-epic-of-gilgamesh.jpg?alt=media",
  },
  {
    id: 5,
    title: "The Book Of Job",
    author: "Unknown",
    realYears: "7th - 4th century BCE",
    year: "-600",
    country: "Achaemenid Empire",
    language: "Hebrew",
    pages: 176,
    wikipediaLink: "https://en.wikipedia.org/wiki/Book_of_Job",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fthe-book-of-job.jpg?alt=media",
  },
  {
    id: 6,
    title: "One Thousand and One Nights",
    author: "Unknown",
    realYears: "700-1500",
    year: "1200",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    language: "Arabic",
    pages: 288,
    wikipediaLink: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fone-thousand-and-one-nights.jpg?alt=media",
  },
  {
    id: 7,
    title: "Njál's Saga",
    author: "Unknown",
    realYears: "13th century",
    year: "1350",
    country: "Iceland",
    language: "Old Norse",
    pages: 384,
    wikipediaLink: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fnjals-saga.jpg?alt=media",
  },
  {
    id: 8,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    realYears: "1813",
    year: "1813",
    country: "United Kingdom",
    language: "English",
    pages: 226,
    wikipediaLink: "https://en.wikipedia.org/wiki/Pride_and_Prejudice",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fpride-and-prejudice.jpg?alt=media",
  },
  {
    id: 9,
    title: "Le Père Goriot",
    author: "Honoré de Balzac",
    realYears: "1835",
    year: "1835",
    country: "France",
    language: "French",
    pages: 443,
    wikipediaLink: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fle-pere-goriot.jpg?alt=media",
  },
  {
    id: 10,
    title: "Molloy, Malone Dies, The Unnamable",
    author: "Samuel Beckett",
    realYears: "1951-53",
    year: "1952",
    country: "Republic of Ireland",
    language: "French, English",
    pages: 256,
    wikipediaLink: "https://en.wikipedia.org/wiki/Molloy_(novel)",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fmolloy-malone-dies-the-unnamable.jpg?alt=media",
  },
  {
    id: 11,
    title: "The Decameron",
    author: "Giovanni Boccaccio",
    realYears: "1349-53",
    year: "1351",
    country: "Italy",
    language: "Italian",
    pages: 1024,
    wikipediaLink: "https://en.wikipedia.org/wiki/The_Decameron",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fthe-decameron.jpg?alt=media",
  },
  {
    id: 12,
    title: "Ficciones",
    author: "Jorge Luis Borges",
    realYears: "1944-86",
    year: "1965",
    country: "Argentina",
    language: "Spanish",
    pages: 224,
    wikipediaLink: "https://en.wikipedia.org/wiki/Ficciones",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fficciones.jpg?alt=media",
  },
  {
    id: 13,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    realYears: "1847",
    year: "1847",
    country: "United Kingdom",
    language: "English",
    pages: 342,
    wikipediaLink: "https://en.wikipedia.org/wiki/Wuthering_Heights",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fwuthering-heights.jpg?alt=media",
  },
  {
    id: 14,
    title: "The Stranger",
    author: "Albert Camus",
    realYears: "1942",
    year: "1942",
    country: "Algeria, French Empire",
    language: "French",
    pages: 185,
    wikipediaLink: "https://en.wikipedia.org/wiki/The_Stranger_(novel)",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fl-etranger.jpg?alt=media",
  },
  {
    id: 15,
    title: "Poems",
    author: "Paul Celan",
    realYears: "1952",
    year: "1952",
    country: "Romania, France",
    language: "German",
    pages: 320,
    wikipediaLink: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fpoems-paul-celan.jpg?alt=media",
  },
  {
    id: 16,
    title: "Journey to the End of the Night",
    author: "Louis-Ferdinand Céline",
    realYears: "1932",
    year: "1932",
    country: "France",
    language: "French",
    pages: 505,
    wikipediaLink:
      "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fvoyage-au-bout-de-la-nuit.jpg?alt=media",
  },
  {
    id: 17,
    title: "Don Quijote De La Mancha",
    author: "Miguel de Cervantes",
    realYears: "1605 (part 1), 1615 (part 2)",
    year: "1610",
    country: "Spain",
    language: "Spanish",
    pages: 1056,
    wikipediaLink: "https://en.wikipedia.org/wiki/Don_Quixote",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fdon-quijote-de-la-mancha.jpg?alt=media",
  },
  {
    id: 18,
    title: "The Canterbury Tales",
    author: "Geoffrey Chaucer",
    realYears: "14th century",
    year: "1450",
    country: "England",
    language: "English",
    pages: 544,
    wikipediaLink: "https://en.wikipedia.org/wiki/The_Canterbury_Tales",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fthe-canterbury-tales.jpg?alt=media",
  },
  {
    id: 19,
    title: "Stories",
    author: "Anton Chekhov",
    realYears: "1886",
    year: "1886",
    country: "Russia",
    language: "Russian",
    pages: 194,
    wikipediaLink:
      "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fstories-of-anton-chekhov.jpg?alt=media",
  },
  {
    id: 20,
    title: "Nostromo",
    author: "Joseph Conrad",
    realYears: "1904",
    year: "1904",
    country: "United Kingdom",
    language: "English",
    pages: 320,
    wikipediaLink: "https://en.wikipedia.org/wiki/Nostromo",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/jaksmok-assigment-be.appspot.com/o/assignment%2Fnostromo.jpg?alt=media",
  },
];
